### ISSUE TITLE
Improving test coverage

### ISSUE THREAD

**Issue by jhsu802701** [minnestar/sessionizer#184]
Test coverage is currently only 52%, down from over 90% in 2015.

I can tackle the issues in this project, but we first need to improve the test coverage to ensure that we don't accidentally break things without realizing it.

**Comment by jhsu802701** [comment]
Use of lib:
```
Scheduling::Context: used in Scheduling::Schedule
Scheduling::Person: not used
Scheduling::Schedule: used in src/lib/tasks/app.rake
Scheduling::SessionSet: used in Scheduling::Person
```

**Comment by unsay** [comment]
Closing. This is generally expected and will be working towards we work on it.
