### ISSUE TITLE
src/lib/tasks/cucumber.rake

### ISSUE THREAD

**Issue by jhsu802701** [minnestar/sessionizer#188]
Is the src/lib/tasks/cucumber.rake script necessary?  I don't see the cucumber gem listed in src/Gemfile or src/Gemfile.lock.  Are there plans to add cucumber back in, or should this script be removed?

**Comment by jcoyne** [comment]
Good spotting. I suspect that's vestigial and can be removed.

**Comment by jhsu802701** [comment]
This is addressed in https://github.com/minnestar/sessionizer/pull/193 .

**Comment by jhsu802701** [comment]
Merged
