### ISSUE TITLE
Do we need Puma?

### ISSUE THREAD

**Issue by jhsu802701** [minnestar/sessionizer#191]
The default WEBrick server is in use.  Rails Tutorial and Heroku recommend using Puma instead for greater web traffic capacity.  Is there a specific reason we're sticking with WEBrick?

https://www.railstutorial.org/book/sign_up#sec-professional_grade_deployment
https://devcenter.heroku.com/articles/ruby-default-web-server#why-not-webrick

**Comment by jcoyne** [comment]
I'm seeing Unicorn in the Gemfile, but I don't think it would be a problem to switch to Puma.

**Comment by pcantrell** [comment]
On Heroku, the `Procfile` has the final word on which server it uses. And yes, it’s currently Unicorn. Which is probably fine, and Puma is probably fine too.

**Comment by jhsu802701** [comment]
If there's no compelling reason to switch from Unicorn to Puma (or anything else), then we might as well just stick with Unicorn.
