### ISSUE TITLE
Add checkbox to new session form for CoC agreement

### ISSUE THREAD

**Issue by jennapederson** [minnestar/sessionizer#218]
Each presenter needs to agree to this events CoC.

https://minnestar.org/coc

How do we enforce this agreement for multiple presenters? Sign in/registration? Or just on new session creation?

**Comment by aackerman** [comment]
It probably makes the most sense to add a `code_of_conduct_agreed` flag to the `participants` table if we want this to be per person agreement into the future. 

Or add the flag to the `presentations` table if we want this to be per person and per session agreement and expect each participant to keep opting in.
