### ISSUE TITLE
Allow editing of summary blurb on home page

### ISSUE THREAD

**Issue by jennapederson** [minnestar/sessionizer#219]
Update the summary (and/or make this editable by an admin) on the home page to reflect what we actually look for in a session and messaging to reiterate compliance with the code of conduct is required of all presenters and their materials.

Check with @jennapederson for context and exact messaging.

Ideally this is easily editable by an admin as it seems to be dynamic.

**Comment by aackerman** [comment]
@jennapederson could you post a screenshot of the summary blurb to help clear things up? I'm not sure that I'm looking at the right thing.

**Comment by jennapederson** [comment]
Main goal here is easy updating of this blurb. It's so out of date right now, but I can see it being slightly more dynamic than changing once every 10 years 😂 

![image](https://user-images.githubusercontent.com/552757/61060071-a4c58580-a3bf-11e9-9811-b8e76d5797f8.png)
