### ISSUE TITLE
Dockerize the app

### ISSUE THREAD

**Issue by jhsu802701** [minnestar/sessionizer#246]
I'd like to Dockerize this app with a Dockerfile and docker-compose.yml file.  This would make the setup process quicker and more efficient than the current Vagrant setup.

**Comment by jcoyne** [comment]
This sounds like an improvement to me. Go for it.

**Comment by tonyc** [comment]
Scope out https://github.com/bitnami/bitnami-docker-rails as a good, well-maintained base image to use. Let 'er rip!

**Comment by unsay** [comment]
We've done away with Vagrant/Docker and went back to the basics, a plain-ol' RoR app w/PostgreSQL dependency. 

refs #316
