### ISSUE TITLE
Update Session button deletes session

### ISSUE THREAD

**Issue by heuermh** [minnestar/sessionizer#253]
Hope this is the right place to submit this issue!

The Update Session button on the MinneBar 15 Session Registration page, after attempting to edit the text and update an already existing session, actually deletes the session instead.

**Comment by pcantrell** [comment]
It is indeed the right place. Thanks! We’re on it.

**Comment by pcantrell** [comment]
@heuermh We've got a fixed deployed. Could you give it a try and let us know if it works from your end?

**Comment by heuermh** [comment]
Thank you @pcantrell @aackerman for the quick response!

It looks like the same thing happened for me with
https://sessions.minnestar.org/sessions/1149/edit

**Comment by pcantrell** [comment]
Ack, I'm so sorry! I kicked off the deploy without actually checking whether it went through — and it didn't. That's what I get for my haste.

The change is deployed, and should work now.

**Comment by heuermh** [comment]
Confirm it works ok now, see attached screen recording.  Only issue is that session https://sessions.minnestar.org/sessions/1152 should be deleted.  😉

**Comment by pcantrell** [comment]
Thanks for checking! Manually deleted that session.

We'll get the delete button back and working properly when there's time.

**Comment by heuermh** [comment]
Thanks again, @pcantrell
