### ISSUE TITLE
Most Minnebar15 sessions gives you "We're sorry, but something went wrong."

### ISSUE THREAD

**Issue by gregdaigle** [minnestar/sessionizer#268]
Click on most sessions and you get the message.

**Comment by pcantrell** [comment]
Already on it

**Comment by pcantrell** [comment]
Should be fixed now. Let me know if you’re still getting this.

**Comment by gregdaigle** [comment]
Looking good.  Thank you Paul.

Greg
____________
Gregory Daigle
612 636-7227
gregdaigle@me.com

**Comment by pcantrell** [comment]
Thanks for reporting it!
