### ISSUE TITLE
Reset password?

### ISSUE THREAD

**Issue by dfrankow** [minnestar/sessionizer#270]
Google has decided my minnestar password is compromised. So, I'd really like to change it, so it stops bothering me.

I visited https://sessions.minnestar.org/password_resets/new, and clicked "Reset password", but I don't get an email. I've checked my spam and trash.

Could it be that the emailer is down?

**Comment by jmichaelward** [comment]
+1. I attempted a password reset today and did not receive any emails to my account, either in my primary inbox or in spam.

**Comment by kristenkinnearohlmann** [comment]
I'm also trying to reset my password so that I may submit a session for Minnebar. I did not receive an email. I also am using a Gmail account. Nothing received to inbox or spam.

**Comment by jennapederson** [comment]
This should be fixed! Thank you for reporting it. Please try again and let us know if you're still having issues.

**Comment by kristenkinnearohlmann** [comment]
Fixed - thank you!
