### ISSUE TITLE
Cannot export events to JSON

### ISSUE THREAD

**Issue by thingles** [minnestar/sessionizer#75]
I went to the URL I've used in the past to export sessions from sessionizer for archival in the wiki.

http://sessions.minnestar.org/events/1.json

This no longer works. Hoping there is just a new URL for this? Would like to get this exported today so I can populate the wiki for adding slideshows or other notes to.

/cc @caseyhelbling

**Comment by thingles** [comment]
This is still throwing a 404. Going to reopen so we don't lose it.

**Comment by thingles** [comment]
@jcoyne @look should this be closed now? I’m still getting an error when hitting http://sessions.minnestar.org/events/1.json

**Comment by jcoyne** [comment]
I don't think this has been deployed yet. I haven't do it at least. I don't believe I have credentials to deploy.

**Comment by thingles** [comment]
@caseyhelbling can you help with deploy?

**Comment by caseyhelbling** [comment]
Done.

On Wed, Apr 15, 2015 at 4:03 PM, Jamie Thingelstad <notifications@github.com
> wrote:

> @caseyhelbling <https://github.com/caseyhelbling> can you help with
> deploy?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/minnestar/sessionizer/issues/75#issuecomment-93568715>
> .
>



-- 
Casey Helbling

*Founder/CEO  ǁ  @softwareforgood **ǁ  612-207-6622 *
*1005 W Franklin Ave, Suite 5, Minneapolis MN, 55405*

**Comment by thingles** [comment]
Thank you @look @jcoyne @caseyhelbling! Minnebar 10 sessions are now in the wiki!

http://wiki.minnestar.org/wiki/MinneBar_10
